"""initial schema

Revision ID: 3d22a1a24f45
Revises: 
Create Date: 2026-08-12 01:11:42.571703
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3d22a1a24f45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_templates'))
    )
    op.create_index(op.f('ix_notification_templates_key'), 'notification_templates', ['key'], unique=True)
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('origin_terminal', sa.String(length=160), nullable=False),
    sa.Column('destination', sa.String(length=160), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_mins', sa.Integer(), nullable=False),
    sa.Column('base_fare_kobo', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    op.create_index(op.f('ix_routes_code'), 'routes', ['code'], unique=True)
    op.create_index(op.f('ix_routes_is_active'), 'routes', ['is_active'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('price_kobo', sa.Integer(), nullable=False),
    sa.Column('ride_credits', sa.Integer(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('perks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans'))
    )
    op.create_index(op.f('ix_subscription_plans_code'), 'subscription_plans', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=24), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('notify_sms', sa.Boolean(), nullable=False),
    sa.Column('notify_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('plate_no', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.Column('range_km', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    op.create_index(op.f('ix_vehicles_plate_no'), 'vehicles', ['plate_no'], unique=True)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_key', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    op.create_index(op.f('ix_webhook_events_event_key'), 'webhook_events', ['event_key'], unique=True)
    op.create_table('whatsapp_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=48), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_sessions'))
    )
    op.create_index(op.f('ix_whatsapp_sessions_phone'), 'whatsapp_sessions', ['phone'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('license_no', sa.String(length=64), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('assigned_vehicle_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], name=op.f('fk_drivers_assigned_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_drivers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers')),
    sa.UniqueConstraint('license_no', name=op.f('uq_drivers_license_no'))
    )
    op.create_index(op.f('ix_drivers_user_id'), 'drivers', ['user_id'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('pickup_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_stops_route_id_routes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stops')),
    sa.UniqueConstraint('route_id', 'order', name='uq_route_stops_route_id_order')
    )
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('credits_total', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('amount_paid_kobo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credits_used <= credits_total', name=op.f('ck_subscriptions_credits_used_within_total')),
    sa.CheckConstraint('credits_used >= 0', name=op.f('ck_subscriptions_credits_used_non_negative')),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_subscriptions_plan_id_subscription_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_expires_at'), 'subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('trip_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('fare_override_kobo', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_trip_templates_driver_id_drivers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_trip_templates_route_id_routes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_trip_templates_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_templates'))
    )
    op.create_index(op.f('ix_trip_templates_is_active'), 'trip_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_trip_templates_route_id'), 'trip_templates', ['route_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('departure_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_estimate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('seats_total', sa.Integer(), nullable=False),
    sa.Column('seats_booked', sa.Integer(), nullable=False),
    sa.Column('fare_kobo', sa.Integer(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_trips_driver_id_drivers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_trips_route_id_routes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['trip_templates.id'], name=op.f('fk_trips_template_id_trip_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_trips_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips')),
    sa.UniqueConstraint('template_id', 'service_date', name='uq_trips_template_id_service_date')
    )
    op.create_index('ix_trips_departure_datetime', 'trips', ['departure_datetime'], unique=False)
    op.create_index(op.f('ix_trips_route_id'), 'trips', ['route_id'], unique=False)
    op.create_index('ix_trips_route_service_date', 'trips', ['route_id', 'service_date'], unique=False)
    op.create_index(op.f('ix_trips_service_date'), 'trips', ['service_date'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_ref', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('passenger_name', sa.String(length=160), nullable=False),
    sa.Column('passenger_phone', sa.String(length=24), nullable=False),
    sa.Column('passenger_email', sa.String(length=255), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('seat_numbers', postgresql.ARRAY(sa.String(length=8)), nullable=False),
    sa.Column('amount_kobo', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('pickup_stop_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pickup_stop_id'], ['route_stops.id'], name=op.f('fk_bookings_pickup_stop_id_route_stops'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_bookings_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_bookings_trip_id_trips'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_booking_ref'), 'bookings', ['booking_ref'], unique=True)
    op.create_index('ix_bookings_passenger_phone', 'bookings', ['passenger_phone'], unique=False)
    op.create_index(op.f('ix_bookings_source'), 'bookings', ['source'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_subscription_id'), 'bookings', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_bookings_trip_id'), 'bookings', ['trip_id'], unique=False)
    op.create_index('ix_bookings_trip_status', 'bookings', ['trip_id', 'status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_notifications_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_notifications_trip_id_trips'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_booking_id'), 'notifications', ['booking_id'], unique=False)
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_trip_id'), 'notifications', ['trip_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('paystack_reference', sa.String(length=80), nullable=False),
    sa.Column('authorization_url', sa.Text(), nullable=True),
    sa.Column('access_code', sa.String(length=80), nullable=True),
    sa.Column('amount_kobo', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('raw_webhook', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_payments_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_paystack_reference'), 'payments', ['paystack_reference'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('qr_payload', sa.Text(), nullable=False),
    sa.Column('qr_signature', sa.String(length=128), nullable=False),
    sa.Column('qr_token', sa.Text(), nullable=False),
    sa.Column('qr_image_path', sa.Text(), nullable=False),
    sa.Column('qr_image_url', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_tickets_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], name=op.f('fk_tickets_checked_in_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_index(op.f('ix_tickets_booking_id'), 'tickets', ['booking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_booking_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_paystack_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_trip_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_booking_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index('ix_bookings_trip_status', table_name='bookings')
    op.drop_index(op.f('ix_bookings_trip_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_subscription_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_source'), table_name='bookings')
    op.drop_index('ix_bookings_passenger_phone', table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_ref'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_service_date'), table_name='trips')
    op.drop_index('ix_trips_route_service_date', table_name='trips')
    op.drop_index(op.f('ix_trips_route_id'), table_name='trips')
    op.drop_index('ix_trips_departure_datetime', table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_trip_templates_route_id'), table_name='trip_templates')
    op.drop_index(op.f('ix_trip_templates_is_active'), table_name='trip_templates')
    op.drop_table('trip_templates')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_expires_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_drivers_user_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_whatsapp_sessions_phone'), table_name='whatsapp_sessions')
    op.drop_table('whatsapp_sessions')
    op.drop_index(op.f('ix_webhook_events_event_key'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate_no'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscription_plans_code'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_routes_is_active'), table_name='routes')
    op.drop_index(op.f('ix_routes_code'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_notification_templates_key'), table_name='notification_templates')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###
