"""service types, passenger sex counts, charter requests

Revision ID: f02a8f8a5bf7
Revises: 3d22a1a24f45
Create Date: 2026-08-15 23:01:16.324904
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f02a8f8a5bf7'
down_revision: Union[str, None] = '3d22a1a24f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charter_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=False),
    sa.Column('contact_phone', sa.String(length=24), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('organisation', sa.String(length=160), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('origin_text', sa.String(length=200), nullable=False),
    sa.Column('destination_text', sa.String(length=200), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('preferred_time', sa.Time(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('return_trip', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quoted_amount_kobo', sa.Integer(), nullable=True),
    sa.Column('quote_notes', sa.Text(), nullable=True),
    sa.Column('quoted_by', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('quoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_charter_requests_driver_id_drivers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quoted_by'], ['users.id'], name=op.f('fk_charter_requests_quoted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_charter_requests_route_id_routes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_charter_requests_trip_id_trips'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_charter_requests_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charter_requests'))
    )
    op.create_index(op.f('ix_charter_requests_contact_phone'), 'charter_requests', ['contact_phone'], unique=False)
    op.create_index(op.f('ix_charter_requests_reference'), 'charter_requests', ['reference'], unique=True)
    op.create_index(op.f('ix_charter_requests_route_id'), 'charter_requests', ['route_id'], unique=False)
    op.create_index(op.f('ix_charter_requests_service_date'), 'charter_requests', ['service_date'], unique=False)
    op.create_index(op.f('ix_charter_requests_status'), 'charter_requests', ['status'], unique=False)
    # NOT NULL columns added to populated tables need a server_default, otherwise
    # the ALTER fails on every existing row.
    op.add_column('bookings', sa.Column('seats_male', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('bookings', sa.Column('seats_female', sa.Integer(), nullable=False, server_default='0'))

    # Bookings taken before demographics were collected stay at 0/0 rather than
    # having a sex invented for them; the constraint allows exactly that case.
    op.create_check_constraint(
        'seats_by_sex_match_total',
        'bookings',
        '(seats_male = 0 AND seats_female = 0) OR (seats_male + seats_female = seats)',
    )

    op.add_column('payments', sa.Column('charter_request_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('provider', sa.String(length=24), nullable=False, server_default='paystack'))
    op.create_index(op.f('ix_payments_charter_request_id'), 'payments', ['charter_request_id'], unique=False)
    op.create_foreign_key(op.f('fk_payments_charter_request_id_charter_requests'), 'payments', 'charter_requests', ['charter_request_id'], ['id'], ondelete='SET NULL')

    op.add_column('routes', sa.Column('service_type', sa.String(length=16), nullable=False, server_default='airport'))
    op.add_column('routes', sa.Column('charter_fare_kobo', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_routes_service_type'), 'routes', ['service_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_service_type'), table_name='routes')
    op.drop_column('routes', 'charter_fare_kobo')
    op.drop_column('routes', 'service_type')
    op.drop_constraint(op.f('fk_payments_charter_request_id_charter_requests'), 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_charter_request_id'), table_name='payments')
    op.drop_column('payments', 'provider')
    op.drop_column('payments', 'charter_request_id')
    op.drop_constraint('ck_bookings_seats_by_sex_match_total', 'bookings', type_='check')
    op.drop_column('bookings', 'seats_female')
    op.drop_column('bookings', 'seats_male')
    op.drop_index(op.f('ix_charter_requests_status'), table_name='charter_requests')
    op.drop_index(op.f('ix_charter_requests_service_date'), table_name='charter_requests')
    op.drop_index(op.f('ix_charter_requests_route_id'), table_name='charter_requests')
    op.drop_index(op.f('ix_charter_requests_reference'), table_name='charter_requests')
    op.drop_index(op.f('ix_charter_requests_contact_phone'), table_name='charter_requests')
    op.drop_table('charter_requests')
    # ### end Alembic commands ###
